version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:11.4-alpine
    ports:
      - "5431:5431"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=teste

  app:
    container_name: app
    build: .
    volumes:
      - ./:/usr/app
    command: npm start
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  postgres-data:
